### ISSUE TITLE
UTC mode 

### ISSUE THREAD

**Issue by jorgeamadosoria** [tcort/handlebars-dateformat#2]
I found that I had an issue using this extension on a mongoose + express app, namely, I got one day less when printing the date object on the page.

I found several suggestions tying this to timezones, and got it fix by using moment on utc mode, but the helper does not have that feature. 
I solved by modifying the index.js as follows:

function dateFormat(date, format, UTC) {
    if (UTC === "utc")
        return moment(date).utc().format(format);
    else
        return moment(date).format(format);
};

It would be great if this could be added as an option, not necessarily this code, but something like it.

**Comment by tcort** [comment]
I've implemented this and published version `1.1.0`.

The `UTC` parameter is an optional boolean (`true` or `false`). It defaults to `false`. See the `README.md` for details.
